name: default
title: Sukhpreet Singh | Front-end Developer & Yoga Instructor
description: >-
    Digital Open Home of Sukhpreet Singh a.k.a `q1b` to bring forth the thoughts
    and share the learnings back to developers.
image:
    src: /og/default/image/src.jpg
    alt: Build the web you want
